### ISSUE TITLE
Change property scopes to protected?

### ISSUE THREAD

**Issue by dlundgren** [assetic-php/assetic#14]
It'd be nice to be able to extend/enhance parts of the library instead of copy/paste to do so.

Would you be open to changing the privates to protected to allow easier extension?

**Comment by bennothommo** [comment]
@dlundgren Feel free to submit a PR with the functions you intend to convert to `protected`, and we'll take a look. I don't see any issue with your suggestion, but we'll need to take a look and ensure it doesn't break anything.

**Comment by stof** [comment]
Note that switching to protected increases the maintenance cost, as any refactoring can then become a BC break a lot more easily (it is very hard to refactor a class using `protected` rather than `private` while maintaining BC, because this is about refactoring a class API and not refactoring internals anymore (and when everything is protected, the inheritance-based API is a lot more leaky than any public API).

**Comment by bennothommo** [comment]
@stof agreed. We'll just have to see what comes in and give it careful consideration on the benefit ratio between maintenance and flexibility.

**Comment by stof** [comment]
for reference, in Symfony, we don't only ask for a list of functions/properties that are requested to become protected. We also ask for a clear use case justifying this (and then, we first evaluate whether there is a better solution for the problem, through decoration or a new extension point before considering allowing inheritance-based extension)

**Comment by dlundgren** [comment]
Thanks for the feedback! I reviewed what I was trying to do, and created a PR with what I was really trying to accomplish.

Basically I would like to get the name and asset object that the `AssetReference` is using.
